version: 2.1

jobs:
  test:
    docker:
      - image: cimg/node:19.0.1
    resource_class: small
    steps:
      - run: |
          echo "This is the best job"
          sleep 33
#      - checkout
#      - run: ls -al /tmp/ftpopomol || true
#      - persist_to_workspace:
#          root: /root/workspace
#          paths:
#            - README.md

  build:
    docker:
      - image: cimg/node:19.0.1
    resource_class: small
    steps:
      - run: echo "Ze build"

# Creating multiple pipelines at the same time with the below config will results in
# all pipelines running test and build but only a single pipeline will run deploy at a time.

workflows:
  main-workflow:
    jobs:
      - test:
          serial-group: << pipeline.project.slug >>/deploy-group
      - build:
          serial-group: << pipeline.project.slug >>/deploy-group
