version: 2.1

jobs:
  test:
    docker:
      - image: cimg/node:19.0.1
    resource_class: small
    steps:
      - run: echo "This is the best job"
#      - checkout
#      - run: ls -al /tmp/ftpopomol || true
#      - persist_to_workspace:
#          root: /root/workspace
#          paths:
#            - README.md

  check:
    docker:
      - image: cimg/node:19.0.1
    resource_class: small
    steps:
      - run: echo "After the approval"
workflows:
  my-workflow:
    jobs:
      - test
      - attend:
          type: approval
          requires:
            - test
      - check:
          requires:
            - attend
