version: 2.1

parameters:
  environment:
    type: string
    default: "prod"  

jobs:
  deploy-job:
    docker:
      # Specify the version you desire here
      # See: https://circleci.com/developer/images/image/cimg/base
      - image: cimg/base:current
    resource_class: small
    steps:
      - run: echo "Hello"

# workflows:
#  my-workflow:
#    jobs:
#      - daily-message:
#         message: echo << parameters.message >>

workflows:
  deploy:
    when:
       equal: [ prod, << pipeline.parameters.environment >> ]
    jobs:
      - deploy-job
