version: 2.1

jobs:
  test:
    docker:
      - image: cimg/node:19.0.1
    steps:
      - checkout
      - run: exit 1
      - persist_to_workspace:
          root: /root/workspace
          paths:
            - README.md
          when: always


workflows:
  my-workflow:
    jobs:
      - test
