version: 2.1

parameters:
  run-build-service-1-job:
    type: string
    default: "second value"

jobs:
  say-hello:
    # Specify the execution environment. You can specify an image from Docker Hub or use one of our convenience images from CircleCI's Developer Hub.
    # See: https://circleci.com/docs/executor-intro/ & https://circleci.com/docs/configuration-reference/#executor-job
    docker:
      # Specify the version you desire here
      # See: https://circleci.com/developer/images/image/cimg/base
      - image: cimg/base:current
    resource_class: small

    steps:
      # Checkout the code as the first step.
      - checkout
      - run:
          name: "Ya better say hello"
          command: "echo Hello, World!"

workflows:
  say-hello-workflow: # This is the name of the workflow, feel free to change it to better match your workflow.
    # Inside the workflow, you define the jobs you want to run.
    jobs:
      - say-hello
